// Generated by https://quicktype.io

export interface AccountByIDResponse {
    data: Data;
}

enum TypeAccount {
    natural = "natural",
    company = "company"
}

export interface Data {
    natureAccount: TypeAccount;
    accountId:     string;
    members:       Member[];
    owner:         Owner;
    createdAt:     CreatedAt;
    agreement:     Agreement;
    questionnaire: Questionnaire;
    id:            string;
}

export interface Agreement {
    content: string;
    id:      string;
}

export interface CreatedAt {
    _seconds:     number;
    _nanoseconds: number;
}

export interface Member {
    dateBirth:    string;
    taxCountry:   string;
    firstName:    string;
    phoneCountry: string;
    city:         string;
    phoneSMS:     boolean;
    documents:    Document[];
    email:        string;
    taxId:        string;
    postalCode:   string;
    streetOne:    string;
    contactId:    string;
    region:       string;
    lastName:     string;
    webhook:      string;
    phoneNumber:  string;
    middleName:   string;
    contactType:  string;
    label:        string;
    country:      string;
    streetTwo:    string;
}

export interface Document {
    label:            string;
    documentId:       string;
    documentSide?:    string;
    taxId:            string;
    file:             string;
    documentCountry:  string;
    isBusinessMember: string;
    documentType:     string;
    description:      string;
}

export interface Owner {
    contactId:       string;
    streetOne:       string;
    contactType:     string;
    phoneNumber:     string;
    documents:       Document[];
    postalCode:      string;
    streetTwo:       string;
    email:           string;
    country:         string;
    taxId:           string;
    phoneCountry:    string;
    regionFormation: string;
    phoneSMS:        boolean;
    name:            string;
    webhook:         string;
    region:          string;
    city:            string;
    taxCountry:      string;
}

export interface Questionnaire {
    purposeAccount:                         string;
    intendedUseAccount:                     string;
    natureBusinessCompany:                  string;
    associationsWithOtherAccounts:          string;
    sourceAssetsAndIncome:                  string;
    anticipatedMonthlyCashVolume:           string;
    anticipatedMonthlyTransactionsOutgoing: string;
    anticipatedTypesAssets:                 string;
    anticipatedTradingPatterns:             string;
    anticipatedMonthlyTransactionsIncoming: string;
}
