// Generated by https://quicktype.io

export interface Document {
    label:            string;
    documentType:     string;
    taxId:            string;
    description:      string;
    file:             string;
    documentId:       string;
    isBusinessMember: string;
    documentCountry:  string;
}
