// Generated by https://quicktype.io

export interface createExchangeResponse {
  message: string
  data: ExchangeData
}

// export interface Data {
//   exchangeId: string
//   amount: string
//   amountIsUnitCount: boolean
//   transactionType: string
//   assetId: string
//   accountId: string
//   status: string
//   baseAmount: number
//   feeAmount: number
//   totalAmount: number
//   unitCount: number
//   feeNoba: number
// }

export interface ExchangeData {
  exchangeId?: string
  id?: string
  status?: string
  created_timestamp?: string
  action?: string
  sourceDetails: {
    walletId: string
    assetCode: string
    amountDebit: number
  }
  destinationDetails: {
    walletId: string
    assetCode: string
    amountCredit: number
  }
  networkFee?: number
  feeNoba: number
}
