// Generated by https://quicktype.io

export interface ExchangeResponse {
  nextPag: number
  count: number
  results: ExchangeCreated[]
}

export interface ExchangeCreated {
  _id: string
  baseAmount: number
  clientId: string
  createdAt: string
  destinationDetails: {
    assetCode: string
    amountCredit: number
    walletId: string
  }
  exchangeId: string
  feeAmount: number
  feeBusinessAllie: number
  feeNoba: number
  sourceDetails: {
    assetCode: string
    amountDebit: number
    walletId: string
  }
  status: string
  totalAmount: number
  acceptedAt: string
  id: string
  networkFee?: number
}

export enum Code {
  Ada = 'ADA',
  Btc = 'BTC',
  Ltc = 'LTC',
  Usdt = 'USDT',
}

export interface AtedAt {
  _seconds: number
  _nanoseconds: number
}

export enum Status {
  Cancel = 'cancel',
  Pending = 'pending',
  Process = 'process',
}

export enum TransactionType {
  Buy = 'buy',
  Sell = 'sell',
}
