// Generated by https://quicktype.io

export interface ExchangeResponse {
  nextPag: string
  prevPag: string
  count: number
  results: ExchangeCreated[]
}

// export interface Result {
//   id: string
//   amountIsUnitCount: boolean
//   createdAt: AtedAt
//   assetId: string
//   unitCount: number
//   status: Status
//   baseAmount: number
//   accountId: string
//   feeAmount: number
//   exchangeId: string
//   totalAmount: number
//   amount: number
//   transactionType: TransactionType
//   code: string
//   updatedAt?: AtedAt
//   tradeId?: null
// }

export interface ExchangeCreated {
  _id: string
  baseAmount: number
  clientId: string
  createdAt: string
  destinationDetails: {
    assetCode: string
    amountCredit: number
    walletId: string
  }
  exchangeId: string
  feeAmount: number
  feeBusinessAllie: number
  feeNoba: number
  sourceDetails: {
    assetCode: string
    amountDebit: number
    walletId: string
  }
  status: string
  totalAmount: number
  acceptedAt: string
  id: string
}

export enum Code {
  Ada = 'ADA',
  Btc = 'BTC',
  Ltc = 'LTC',
  Usdt = 'USDT',
}

export interface AtedAt {
  _seconds: number
  _nanoseconds: number
}

export enum Status {
  Cancel = 'cancel',
  Pending = 'pending',
  Process = 'process',
}

export enum TransactionType {
  Buy = 'buy',
  Sell = 'sell',
}
