export enum StatusCard {
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
  CANCELLED = 'CANCELLED',
  INACTIVE = 'INACTIVE',
  DELETE = 'DELETE',
  WAITING_DATA = 'WAITING_DATA',
  WAITING_ACTIVATION = 'WAITING_ACTIVATION',
}
