export const deletedCountries = () => {
  return {
    countries: [
      'AFGHANISTAN',
      'ARABIA SAUDITA',
      'BANGLADESH',
      'BIELORRUSIA',
      'BIRMANIA',
      'BOLIVIA',
      'BURKINA FASO',
      'CABO VERDE',
      'CAMERÚN',
      'COREA DEL NORTE',
      'CONGO',
      'REPÚBLICA DEMOCRÁTICA DEL CONGO',
      'COSTA DE MARFIL',
      'CUBA',
      'EGIPTO',
      'EMIRATOS ARABES UNIDOS',
      'ERITREA',
      'ETIOPÍA',
      'RUSIA',
      'GHANA',
      'HAITI',
      'HONDURAS',
      'IRAK',
      'IRAN',
      'KENIA',
      'CATAR',
      'LESOTO',
      'LIBERIA',
      'LIBIA',
      'LÍBANO',
      'MALÍ',
      'MARRUECOS',
      'MOZAMBIQUE',
      'NAMIBIA',
      'NEPAL',
      'NIGER',
      'PAKISTAN',
      'SIRIA',
      'REPÚBLICA CENTROAFRICANA',
      'SAHARA OCCIDENTAL',
      'SENEGAL',
      'SIERRA LEONA',
      'SOMALIA',
      'SRI LANKA',
      'SUDÁN',
      'SUDÁN DEL SUR',
      'TANZANIA',
      'UCRANIA',
      'UGANDA',
      'VENEZUELA',
      'YEMEN',
      'ZAMBIA',
      'ZIMBABUE',
    ],
  }
}
