export const deletedCountries = () => {
    return {
        countries: [
            "ABKHAZIA",
            "AFGHANISTAN",
            "ALBANIA",
            "ANGOLA",
            "BELARUS",
            "BOSNIA Y HERZEGOVINA",
            "BURMA (MYANMAR)",
            "AGAIN",
            "CENTRAL AFRICAN REPUBLIC",
            "COLOMBIA",
            "CUBA",
            "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA (NORTH KOREA)",
            "DEMOCRATIC REPUBLIC OF CONGO",
            "ETHIOPIA",
            "ERITREA",
            "GUINEA",
            "GUINEA-BISSAU",
            "HAITI",
            "IRAN",
            "IRAQ",
            "IVORY COAST (IVORY COAST)",
            "KOSOVO",
            "LEBANON",
            "LIBERIA",
            "LIBYA",
            "MACEDONIA",
            "SMALL",
            "MYANMAR (BURMA)",
            "NAGORNO-KARABAJ",
            "NICARAGUA",
            "NORTHERN CYPRUS",
            "PAKISTAN",
            "RUSSIA",
            "SAHARAWI ARAB DEMOCRATIC REPUBLIC",
            "SOMALIA",
            "SOMALILAND",
            "SOUTH OSSETIA",
            "SOUTH SUDAN",
            "SUDAN",
            "SYRIA",
            "SERBIA",
            "SIERRA LEONA",
            "UKRAINE (OCCUPIED TERRITORIES)",
            "VENEZUELA",
            "YEMEN",
            "ZIMBABWE"
        ],
    }
}
